# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6336c119e792084abf542b39d2ca0bfcaeeb9c782011a71f3ebdab782bf3fd6e5b40344988044f1fc4c0d4381b32c8c303bbdeb8c4ba5a0c07d0ebaf6f3bb84a

test:
  secret_key_base: 693b5cffa08b28d6eabc0232d0f265eb04e12d50791f263bc9f68b75d5db3d5fb0d047eadbee6324c32b469b8ee747fcb4c26bdc17e7df488f6fe6ec0cc10925

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
